### PR TITLE
Spinners strings defined in a Dict

### PR DESCRIPTION
**Pull request by curio-sitas**
Defining Spinners in a Dict avoids to write ifelse conditions and compacts the code of `get_named_string()`.

```julia
get_named_string(x::Symbol) = get(SPINNERS, x, "?")

SPINNERS = Dict(
	:arrow => "←↖↑↗→↘↓↙",
	:bar => "▁▂▃▄▅▆▇█▇▆▅▄▃▂▁",
	:blink => "⊙◡⊙⊙◡⊙⊙⊙⊙⊙⊙⊙",
        ...)
```

### CODE REVIEW

**Review by AshlinHarris — APPROVED** [review]
Looks great. Thank you very much for the excellent contribution!

The default value for the Spinner has been changed from "? " to "?", which is fine. Now it will render as a static question mark instead of a flashing one.

**Comment by AshlinHarris** [comment]
I'm not sure why the CI hasn't run. The workflow should run on any pull request to the main branch, and I can't find a setting on GitHub that allows this for new contributors or an option to override the default.

**Review by AshlinHarris — APPROVED** [review]

**Comment by curio-sitas** [comment]
> I'm not sure why the CI hasn't run. The workflow should run on any pull request to the main branch, and I can't find a setting on GitHub that allows this for new contributors or an option to override the default.

Look's like the CI needs more approvals ?

**Comment by AshlinHarris** [comment]
> Look's like the CI needs more approvals ?

As far as I can tell, that isn't the issue. Approvals aren't required as part of branch protection for this repo. I looked over [the relevant documentation](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), but there is no option to "Workflow(s) awaiting approval" section. It looks like the checks are still just waiting to be run.

I'll try making a commit to see if that moves things along.

**Review by AshlinHarris — APPROVED** [review]

**Review by AshlinHarris — APPROVED** [review]

**Comment by AshlinHarris** [comment]
@curio-sitas, if the workflow doesn't start soon, I'll just bypass the branch protection and merge everything manually. Thanks again for your contribution!

By the way, I plan to change how the spinner is generated. Instead of shelling out to make a new process, I'll be using distributed threads. As a result, I might not be able to approve major changes until after I push my own. But localized revisions like this one are always appreciated!

**Review by AshlinHarris — APPROVED** [review]

**Comment by curio-sitas** [comment]
> @curio-sitas, if the workflow doesn't start soon, I'll just bypass the branch protection and merge everything manually. Thanks again for your contribution!
> 
> By the way, I plan to change how the spinner is generated. Instead of shelling out to make a new process, I'll be using distributed threads. As a result, I might not be able to approve major changes until after I push my own. But localized revisions like this one are always appreciated!

I'm interesting to see that ! Also, in the same mind than this PR i am interested to add more Spinners in the Dict (#36)

**Comment by AshlinHarris** [comment]
@curio-sitas My bad. I forgot that I had disabled the workflow from the actions menu, since I was planning to make breaking changes. I wish there was some indicator from this screen...

Thanks for your help. I'm rather new to Julia, as you could probably tell from all of my `ifelse` conditions. So, I'm always grateful for any contributions!

**Pull request merged**
